# Generated by Django 4.0.4 on 2022-05-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sent_from',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sent_to',
        ),
    ]
